# Azure build pipeline to validate a secret from a variable group

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: <target-variable-group>

steps:
- script: |
    myVar="$(AZURE_STATIC_WEB_APPS_API_TOKEN)" 
    len=${#myVar} # Get the length of the variable
    half=$((len / 2))   # Split point (integer division)

    # Split the string
    myVar_1=${myVar:0:half}
    myVar_2=${myVar:half}

    # Print results
    appToken=$myVar_1"|"$myVar_2
    echo "App token: $appToken"
  displayName: 'Secret validator'